//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.05.16 at 05:29:02 PM MESZ
//


package org.apache.ode.activityrecovery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="retryFor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="retryDelay" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="faultOnFailure" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "failureHandling")
public class FailureHandling {

    protected Integer retryFor;
    protected Integer retryDelay;
    protected Boolean faultOnFailure;

    /**
     * Gets the value of the retryFor property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getRetryFor() {
        return this.retryFor;
    }

    /**
     * Sets the value of the retryFor property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setRetryFor(final Integer value) {
        this.retryFor = value;
    }

    /**
     * Gets the value of the retryDelay property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getRetryDelay() {
        return this.retryDelay;
    }

    /**
     * Sets the value of the retryDelay property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setRetryDelay(final Integer value) {
        this.retryDelay = value;
    }

    /**
     * Gets the value of the faultOnFailure property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isFaultOnFailure() {
        return this.faultOnFailure;
    }

    /**
     * Sets the value of the faultOnFailure property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setFaultOnFailure(final Boolean value) {
        this.faultOnFailure = value;
    }

}
