//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.02 at 04:58:44 PM CEST
//

package org.oasis_open.docs.tosca.ns._2011._12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for tRelationshipTypeImplementation complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tRelationshipTypeImplementation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/tosca/ns/2011/12}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="Tags" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tTags" minOccurs="0"/>
 *         &lt;element name="DerivedFrom" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="relationshipTypeImplementationRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RequiredContainerFeatures" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tRequiredContainerFeatures" minOccurs="0"/>
 *         &lt;element name="ImplementationArtifacts" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tImplementationArtifacts" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="targetNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="relationshipType" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="abstract" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tBoolean" default="no" />
 *       &lt;attribute name="final" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tBoolean" default="no" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRelationshipTypeImplementation",
    propOrder = {"tags", "derivedFrom", "requiredContainerFeatures", "implementationArtifacts"})
public class TRelationshipTypeImplementation extends TExtensibleElements {

    @XmlElement(name = "Tags")
    protected TTags tags;
    @XmlElement(name = "DerivedFrom")
    protected TRelationshipTypeImplementation.DerivedFrom derivedFrom;
    @XmlElement(name = "RequiredContainerFeatures")
    protected TRequiredContainerFeatures requiredContainerFeatures;
    @XmlElement(name = "ImplementationArtifacts")
    protected TImplementationArtifacts implementationArtifacts;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String targetNamespace;
    @XmlAttribute(required = true)
    protected QName relationshipType;
    @XmlAttribute(name = "abstract")
    protected TBoolean _abstract;
    @XmlAttribute(name = "final")
    protected TBoolean _final;

    /**
     * Gets the value of the tags property.
     *
     * @return possible object is {@link TTags }
     */
    public TTags getTags() {
        return this.tags;
    }

    /**
     * Sets the value of the tags property.
     *
     * @param value allowed object is {@link TTags }
     */
    public void setTags(final TTags value) {
        this.tags = value;
    }

    /**
     * Gets the value of the derivedFrom property.
     *
     * @return possible object is {@link TRelationshipTypeImplementation.DerivedFrom }
     */
    public TRelationshipTypeImplementation.DerivedFrom getDerivedFrom() {
        return this.derivedFrom;
    }

    /**
     * Sets the value of the derivedFrom property.
     *
     * @param value allowed object is {@link TRelationshipTypeImplementation.DerivedFrom }
     */
    public void setDerivedFrom(final TRelationshipTypeImplementation.DerivedFrom value) {
        this.derivedFrom = value;
    }

    /**
     * Gets the value of the requiredContainerFeatures property.
     *
     * @return possible object is {@link TRequiredContainerFeatures }
     */
    public TRequiredContainerFeatures getRequiredContainerFeatures() {
        return this.requiredContainerFeatures;
    }

    /**
     * Sets the value of the requiredContainerFeatures property.
     *
     * @param value allowed object is {@link TRequiredContainerFeatures }
     */
    public void setRequiredContainerFeatures(final TRequiredContainerFeatures value) {
        this.requiredContainerFeatures = value;
    }

    /**
     * Gets the value of the implementationArtifacts property.
     *
     * @return possible object is {@link TImplementationArtifacts }
     */
    public TImplementationArtifacts getImplementationArtifacts() {
        return this.implementationArtifacts;
    }

    /**
     * Sets the value of the implementationArtifacts property.
     *
     * @param value allowed object is {@link TImplementationArtifacts }
     */
    public void setImplementationArtifacts(final TImplementationArtifacts value) {
        this.implementationArtifacts = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     */
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the targetNamespace property.
     *
     * @return possible object is {@link String }
     */
    public String getTargetNamespace() {
        return this.targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTargetNamespace(final String value) {
        this.targetNamespace = value;
    }

    /**
     * Gets the value of the relationshipType property.
     *
     * @return possible object is {@link QName }
     */
    public QName getRelationshipType() {
        return this.relationshipType;
    }

    /**
     * Sets the value of the relationshipType property.
     *
     * @param value allowed object is {@link QName }
     */
    public void setRelationshipType(final QName value) {
        this.relationshipType = value;
    }

    /**
     * Gets the value of the abstract property.
     *
     * @return possible object is {@link TBoolean }
     */
    public TBoolean getAbstract() {
        if (this._abstract == null) {
            return TBoolean.NO;
        } else {
            return this._abstract;
        }
    }

    /**
     * Sets the value of the abstract property.
     *
     * @param value allowed object is {@link TBoolean }
     */
    public void setAbstract(final TBoolean value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the final property.
     *
     * @return possible object is {@link TBoolean }
     */
    public TBoolean getFinal() {
        if (this._final == null) {
            return TBoolean.NO;
        } else {
            return this._final;
        }
    }

    /**
     * Sets the value of the final property.
     *
     * @param value allowed object is {@link TBoolean }
     */
    public void setFinal(final TBoolean value) {
        this._final = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="relationshipTypeImplementationRef" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DerivedFrom {

        @XmlAttribute(required = true)
        protected QName relationshipTypeImplementationRef;

        /**
         * Gets the value of the relationshipTypeImplementationRef property.
         *
         * @return possible object is {@link QName }
         */
        public QName getRelationshipTypeImplementationRef() {
            return this.relationshipTypeImplementationRef;
        }

        /**
         * Sets the value of the relationshipTypeImplementationRef property.
         *
         * @param value allowed object is {@link QName }
         */
        public void setRelationshipTypeImplementationRef(final QName value) {
            this.relationshipTypeImplementationRef = value;
        }
    }
}
