version: '3'
services:
  engine-ia:
    image: opentosca/engine-ia:latest
    ports:
      - '8099:8080'
  engine-plan:
    image: opentosca/ode:latest
    environment:
      _JAVA_OPTIONS: "-Xmx3048m -Xms512m -Xss4m"
    ports:
      - '9763:9763'
  engine-plan-bpmn:
    image: opentosca/camunda-bpmn:latest
    ports:
      - '8092:8080'
