version: '3'
services:
  engine-ia:
    image: opentosca/engine-ia:latest
    ports:
      - '8099:8080'
    networks:
      - opentosca
  engine-plan:
    image: opentosca/ode:latest
    ports:
      - '9763:9763'
    networks:
      - opentosca
    image: opentosca/engine-ia:latest
    ports:
      - '8090:8080'
    networks:
      - opentosca
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    environment:
      - PORT=2375
      - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
    networks:
      - opentosca
    ports:
      - '2222:2375'
      - '9990-9999:9990-9999'
networks:
  opentosca:
    driver: bridge
