version: '3'
services:
  engine-ia-java8:
    image: opentosca/engine-ia:latest-jdk8
    ports:
      - '8098:8080'
  engine-ia-java17:
    image: opentosca/engine-ia:latest-jdk17
    ports:
      - '8099:8080'
  engine-plan:
    image: opentosca/ode:latest
    environment:
      _JAVA_OPTIONS: "-Xmx3048m -Xms512m -Xss4m"
    ports:
      - '9763:9763'
  engine-plan-bpmn:
    image: opentosca/camunda-bpmn:latest
    ports:
      - '8092:8080'
  container-repository:
    image: opentosca/winery:latest
    environment:
      WINERY_PORT: 8091
      WORKFLOWMODELER_PORT: 8091
      TOPOLOGYMODELER_PORT: 8091
      WINERY_REPOSITORY_URL: https://github.com/OpenTOSCA/tosca-definitions-management-features
    ports:
      - '8091:8080'