//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 05:29:02 PM MESZ 
//


package org.apache.ode.schemas.dd._2007._03;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tProcessEvents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tProcessEvents">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apache.org/ode/schemas/dd/2007/03}tEnableEventList">
 *       &lt;sequence>
 *         &lt;element name="scope-events" type="{http://www.apache.org/ode/schemas/dd/2007/03}tScopeEvents" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="generate">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="all"/>
 *             &lt;enumeration value="none"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tProcessEvents", propOrder = {
    "scopeEvents"
})
public class TProcessEvents
    extends TEnableEventList
{

    @XmlElement(name = "scope-events")
    protected List<TScopeEvents> scopeEvents;
    @XmlAttribute
    protected String generate;

    /**
     * Gets the value of the scopeEvents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scopeEvents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScopeEvents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TScopeEvents }
     * 
     * 
     */
    public List<TScopeEvents> getScopeEvents() {
        if (scopeEvents == null) {
            scopeEvents = new ArrayList<TScopeEvents>();
        }
        return this.scopeEvents;
    }

    /**
     * Gets the value of the generate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerate() {
        return generate;
    }

    /**
     * Sets the value of the generate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerate(String value) {
        this.generate = value;
    }

}
