//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.07.05 at 09:07:58 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://collaboration.org/schema",
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opentosca.bus.management.service.impl.collaboration.model;
