/**
 *
 */
package org.opentosca.planbuilder.service;

import java.util.HashMap;
import java.util.Map;

import org.opentosca.planbuilder.service.model.PlanGenerationState;

/**
 * Copyright 2015 IAAS University of Stuttgart <br>
 * <br>
 *
 * <p>
 * Simple implementation for storing the tasks generated by the PlanBuilder service
 * </p>
 *
 * @author Kalman Kepes - kepeskn@studi.informatik.uni-stuttgart.de
 *
 */
public class RunningTasks {

    public static Map<String, PlanGenerationState> tasks = new HashMap<>();

    public static String generateId() {
        final String newId = String.valueOf(System.currentTimeMillis());
        if (RunningTasks.tasks.containsKey(newId)) {
            return RunningTasks.generateId();
        } else {
            return newId;
        }
    }
}
