//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 02:34:50 PM CEST 
//


package org.opentosca.model.consolidatedtosca;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opentosca.model.consolidatedtosca package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opentosca.model.consolidatedtosca
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsolidatedPolicy }
     * 
     */
    public ConsolidatedPolicy createConsolidatedPolicy() {
        return new ConsolidatedPolicy();
    }

    /**
     * Create an instance of {@link ConsolidatedPolicies }
     * 
     */
    public ConsolidatedPolicies createConsolidatedPolicies() {
        return new ConsolidatedPolicies();
    }

    /**
     * Create an instance of {@link ConsolidatedPolicy.Properties }
     * 
     */
    public ConsolidatedPolicy.Properties createConsolidatedPolicyProperties() {
        return new ConsolidatedPolicy.Properties();
    }

    /**
     * Create an instance of {@link ConsolidatedPolicy.PolicyTemplateSpecificContent }
     * 
     */
    public ConsolidatedPolicy.PolicyTemplateSpecificContent createConsolidatedPolicyPolicyTemplateSpecificContent() {
        return new ConsolidatedPolicy.PolicyTemplateSpecificContent();
    }

    /**
     * Create an instance of {@link PublicPlan }
     * 
     */
    public PublicPlan createPublicPlan() {
        return new PublicPlan();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link PublicPlans }
     * 
     */
    public PublicPlans createPublicPlans() {
        return new PublicPlans();
    }

}
