//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 02:34:50 PM CEST 
//


package org.opentosca.model.consolidatedtosca;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InputParameter" type="{http://www.opentosca.org/ConsolidatedTOSCA}Parameter" maxOccurs="unbounded"/>
 *         &lt;element name="OutputParameter" type="{http://www.opentosca.org/ConsolidatedTOSCA}Parameter" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CSARID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PlanType" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="InternalPlanID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="PlanID" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="InternalInstanceInternalID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="InterfaceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OperationName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InputMessageID" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="OutputMessageID" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="PlanLanguage" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="isActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hasFailed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputParameter",
    "outputParameter"
})
@XmlRootElement(name = "PublicPlan", namespace = "http://www.opentosca.org/ConsolidatedTOSCA")
public class PublicPlan {

    @XmlElement(name = "InputParameter", namespace = "http://www.opentosca.org/ConsolidatedTOSCA", required = true)
    protected List<Parameter> inputParameter;
    @XmlElement(name = "OutputParameter", namespace = "http://www.opentosca.org/ConsolidatedTOSCA", required = true)
    protected List<Parameter> outputParameter;
    @XmlAttribute(name = "CSARID", required = true)
    protected String csarid;
    @XmlAttribute(name = "PlanType", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String planType;
    @XmlAttribute(name = "InternalPlanID", required = true)
    protected int internalPlanID;
    @XmlAttribute(name = "PlanID", required = true)
    protected QName planID;
    @XmlAttribute(name = "InternalInstanceInternalID", required = true)
    protected int internalInstanceInternalID;
    @XmlAttribute(name = "InterfaceName", required = true)
    protected String interfaceName;
    @XmlAttribute(name = "OperationName", required = true)
    protected String operationName;
    @XmlAttribute(name = "InputMessageID", required = true)
    protected QName inputMessageID;
    @XmlAttribute(name = "OutputMessageID", required = true)
    protected QName outputMessageID;
    @XmlAttribute(name = "PlanLanguage", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String planLanguage;
    @XmlAttribute(name = "isActive", required = true)
    protected boolean isActive;
    @XmlAttribute(name = "hasFailed", required = true)
    protected boolean hasFailed;

    /**
     * Gets the value of the inputParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     * 
     * 
     */
    public List<Parameter> getInputParameter() {
        if (inputParameter == null) {
            inputParameter = new ArrayList<Parameter>();
        }
        return this.inputParameter;
    }

    /**
     * Gets the value of the outputParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     * 
     * 
     */
    public List<Parameter> getOutputParameter() {
        if (outputParameter == null) {
            outputParameter = new ArrayList<Parameter>();
        }
        return this.outputParameter;
    }

    /**
     * Gets the value of the csarid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSARID() {
        return csarid;
    }

    /**
     * Sets the value of the csarid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSARID(String value) {
        this.csarid = value;
    }

    /**
     * Gets the value of the planType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanType() {
        return planType;
    }

    /**
     * Sets the value of the planType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanType(String value) {
        this.planType = value;
    }

    /**
     * Gets the value of the internalPlanID property.
     * 
     */
    public int getInternalPlanID() {
        return internalPlanID;
    }

    /**
     * Sets the value of the internalPlanID property.
     * 
     */
    public void setInternalPlanID(int value) {
        this.internalPlanID = value;
    }

    /**
     * Gets the value of the planID property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getPlanID() {
        return planID;
    }

    /**
     * Sets the value of the planID property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setPlanID(QName value) {
        this.planID = value;
    }

    /**
     * Gets the value of the internalInstanceInternalID property.
     * 
     */
    public int getInternalInstanceInternalID() {
        return internalInstanceInternalID;
    }

    /**
     * Sets the value of the internalInstanceInternalID property.
     * 
     */
    public void setInternalInstanceInternalID(int value) {
        this.internalInstanceInternalID = value;
    }

    /**
     * Gets the value of the interfaceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * Sets the value of the interfaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceName(String value) {
        this.interfaceName = value;
    }

    /**
     * Gets the value of the operationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * Sets the value of the operationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationName(String value) {
        this.operationName = value;
    }

    /**
     * Gets the value of the inputMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getInputMessageID() {
        return inputMessageID;
    }

    /**
     * Sets the value of the inputMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setInputMessageID(QName value) {
        this.inputMessageID = value;
    }

    /**
     * Gets the value of the outputMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getOutputMessageID() {
        return outputMessageID;
    }

    /**
     * Sets the value of the outputMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setOutputMessageID(QName value) {
        this.outputMessageID = value;
    }

    /**
     * Gets the value of the planLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanLanguage() {
        return planLanguage;
    }

    /**
     * Sets the value of the planLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanLanguage(String value) {
        this.planLanguage = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the hasFailed property.
     * 
     */
    public boolean isHasFailed() {
        return hasFailed;
    }

    /**
     * Sets the value of the hasFailed property.
     * 
     */
    public void setHasFailed(boolean value) {
        this.hasFailed = value;
    }

}
