//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.25 at 04:54:56 PM CET
//

package org.opentosca.bus.application.api.soaphttp.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for invokeMethodWithServiceInstanceIDResponse complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="invokeMethodWithServiceInstanceIDResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invokeMethodWithServiceInstanceIDResponse", propOrder = {"requestID"})
public class InvokeMethodWithServiceInstanceIDResponse {

    @XmlElement(required = true)
    protected String requestID;

    /**
     * Gets the value of the requestID property.
     *
     * @return possible object is {@link String }
     */
    public String getRequestID() {
        return this.requestID;
    }

    /**
     * Sets the value of the requestID property.
     *
     * @param value allowed object is {@link String }
     */
    public void setRequestID(final String value) {
        this.requestID = value;
    }
}
