//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.07.29 at 03:39:23 PM MESZ
//

package org.opentosca.bus.management.invocation.plugin.rest.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ParamsType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="ParamsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="queryString"/>
 *     &lt;enumeration value="payload"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "ParamsType")
@XmlEnum
public enum ParamsType {

    @XmlEnumValue("queryString")
    QUERY_STRING("queryString"), @XmlEnumValue("payload")
    PAYLOAD("payload");
    private final String value;

    ParamsType(final String v) {
        this.value = v;
    }

    public String value() {
        return this.value;
    }

    public static ParamsType fromValue(final String v) {
        for (final ParamsType c : ParamsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
