//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.05.16 at 05:29:02 PM MESZ
//

package org.apache.ode.schemas.dd._2007._03;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Message exchange interceptor configuration.
 *
 *
 * <p>
 * Java class for tMexInterceptor complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tMexInterceptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="class-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMexInterceptor", propOrder = {"className"})
public class TMexInterceptor {

    @XmlElement(name = "class-name", required = true)
    protected String className;

    /**
     * Gets the value of the className property.
     *
     * @return possible object is {@link String }
     */
    public String getClassName() {
        return this.className;
    }

    /**
     * Sets the value of the className property.
     *
     * @param value allowed object is {@link String }
     */
    public void setClassName(final String value) {
        this.className = value;
    }
}
