//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.02 at 04:58:44 PM CEST
//

package org.oasis_open.docs.tosca.ns._2011._12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for tImplementationArtifact complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tImplementationArtifact">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/tosca/ns/2011/12}tExtensibleElements">
 *       &lt;attribute name="interfaceName" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="operationName" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="artifactType" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="artifactRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tImplementationArtifact")
@XmlSeeAlso( {org.oasis_open.docs.tosca.ns._2011._12.TImplementationArtifacts.ImplementationArtifact.class})
public class TImplementationArtifact extends TExtensibleElements {

    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String interfaceName;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String operationName;
    @XmlAttribute(required = true)
    protected QName artifactType;
    @XmlAttribute
    protected QName artifactRef;

    /**
     * Gets the value of the interfaceName property.
     *
     * @return possible object is {@link String }
     */
    public String getInterfaceName() {
        return this.interfaceName;
    }

    /**
     * Sets the value of the interfaceName property.
     *
     * @param value allowed object is {@link String }
     */
    public void setInterfaceName(final String value) {
        this.interfaceName = value;
    }

    /**
     * Gets the value of the operationName property.
     *
     * @return possible object is {@link String }
     */
    public String getOperationName() {
        return this.operationName;
    }

    /**
     * Sets the value of the operationName property.
     *
     * @param value allowed object is {@link String }
     */
    public void setOperationName(final String value) {
        this.operationName = value;
    }

    /**
     * Gets the value of the artifactType property.
     *
     * @return possible object is {@link QName }
     */
    public QName getArtifactType() {
        return this.artifactType;
    }

    /**
     * Sets the value of the artifactType property.
     *
     * @param value allowed object is {@link QName }
     */
    public void setArtifactType(final QName value) {
        this.artifactType = value;
    }

    /**
     * Gets the value of the artifactRef property.
     *
     * @return possible object is {@link QName }
     */
    public QName getArtifactRef() {
        return this.artifactRef;
    }

    /**
     * Sets the value of the artifactRef property.
     *
     * @param value allowed object is {@link QName }
     */
    public void setArtifactRef(final QName value) {
        this.artifactRef = value;
    }
}
