# This workflow will build the Container and push a corresponding Docker image to Dockerhub
name: Push stable docker image to Dockerhub

on:
  push:
    branches: stable
    tags:
      - "v*.*.*"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set branch name output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set tag version output
        id: vars2
        run: echo ::set-output name=tagversion::${git describe --tags `git rev-list --tags --max-count=1`}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push version of Container
        if: ${{ steps.vars.outputs.tag == 'stable' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: opentosca/container:${{ steps.vars2.outputs.tagversion }}
